# % Generated by cnd: do not edit by hand

#' @name cndSimpleExample-cnd-conditions
#' @aliases cndSimpleExample-cnd-conditions cndSimpleExample:bad_argument bad_argument cndSimpleExample:bad_argument/error
#' @title Conditions for `cndSimpleExample`
#'
#' @details
#'   The following conditions are defined in the `{cndSimpleExample}` package.
#'
#' @section [`{cnd}`][cnd-package]:
#'   These conditions are made with the `{cnd}` package though the use of
#'   [cnd::condition()].
#'
#' @section `{cndSimpleExample}` conditions:
#'
#'   \subsection{`cndSimpleExample:bad_argument/error`}{
#'   \describe{
#'     \item{package}{`{cndSimpleExample}`}
#'     \item{class}{`cndSimpleExample:bad_argument`}
#'     \item{type}{**error**}
#'   }
#'   x should be `TRUE`
#'  }
#'
#' @seealso [cnd::cnd-package] [cnd::condition]
#' @keywords internal
#'
NULL
