library(testthat)

scrub_environment_code <- function(x) {
  # macos: 9
  # linux: 12
  # windows: 16
  m <- regexpr("(?<=<environment: 0x)[0-9a-f]+(?=>)", x, perl = TRUE)
  regmatches(x, m) <- strrep("0", max(0, 12L))
  x
}

skip_if_no_cep <- function() {
  skip_if_not(dir.exists(cep_dir()), "tools/cep package directory not found")
}

here <- function(...) {
  skip_if_not_installed("here")
  here::here(...)
}

cep_dir <- function() {
  here("tools/cep")
}

test_cep <- function() {
  skip_if_not_installed("pkgload")
  skip_if_no_cep()
  cep <- suppress_cnd_conditions(
    pkgload::load_all(cep_dir(), attach = FALSE, quiet = TRUE)$env
  )
  expect_type(conditions(cep$example_function), "list")
  expect_error(cep$example_function(TRUE), NA)
  expect_error(cep$example_function(0), class = "cep:bad_argument")
}

test_documentation <- function(package) {
  skip_if_not_installed("here")

  wd <- switch(
    package,
    cnd = here(),
    cep = cep_dir(),
    stop("not a valid package: ", package)
  )

  cwd <- setwd(wd)
  on.exit(setwd(cwd))

  dir <- tempfile("cnd_dir_")
  on.exit(unlink(dir, TRUE), add = TRUE)
  dir.create(dir, showWarnings = FALSE)
  # path to where teh documentation will be sent
  path <- tempfile("cnd_documentation_", dir, ".R")

  # extra file to trigger cleanup
  temp <- tempfile("cnd_auto_generated_", dir, ".R")
  writeLines("# % Generated by cnd: do not edit by hand", temp)

  suppress_cnd_conditions(
    expect_message(
      expect_condition(
        expect_identical(cnd_document(package = package, file = path), path),
        class = "cnd:cnd_generated_write"
      ),
      class = "cnd:cnd_generated_cleanup"
    )
  )

  is_ci_windows <-
    Sys.info()[["sysname"]] == "Windows" &&
    # GitHub should set CI to 'true'
    isTRUE(as.logical(Sys.getenv("CI", "false")))

  # no changes
  expect_no_condition(
    withCallingHandlers(
      cnd_document(package = package, file = path),
      # line endings on CI Windows might be throwing off the check.  For now,
      # these are simply going to be muffled
      "cnd:cnd_generated_cleanup" = function(c) {
        if (is_ci_windows) tryInvokeRestart("muffleMessage")
      },
      "cnd:cnd_generated_write" = function(c) {
        if (is_ci_windows) tryInvokeRestart("muffleCondition")
      }
    )
  )

  skip_if_not_installed("roxygen2")
  parsed <- roxygen2::parse_text(readLines(path)[-1:-2], test_env())
  expect_failure(expect_identical(parsed, list()))
}

local_registry <- function(name = basename(tempfile(""))) {
  registrar$add(name)
  do <- as.call(list(function() registrar$remove(name)))
  do.call(on.exit, list(do), envir = parent.frame())
  registrar$get(name)
}

with_op <- function(op, expr) {
  op <- as.list(op)
  old <- options(op)
  on.exit(options(old))
  force(expr)
}

check_rcmdcheck <- function() {
  skip_if_not_installed("rcmdcheck")
  skip_if_no_cep()
  expect_no_error(
    rcmdcheck::rcmdcheck(
      cep_dir(),
      quiet = TRUE,
      args = c("--no-manual", "--no-vignettes"),
      error_on = "warning"
    )
  )
}
