# % Generated by cnd: do not edit by hand

#' @name t0-cnd-conditions
#' @aliases t0-cnd-conditions t0:bad_argument bad_argument t0:bad_argument/error
#' @title Conditions for `t0`
#'
#' @details
#'   The following conditions are defined in the `{t0}` package.
#'
#' @section `{cnd}`:
#'   These conditions are made with the [`{cnd}`][cnd-package] package though
#'   the use of [cnd::condition()].
#'
#' @section `{t0}` conditions:
#'
#'   \subsection{`t0:bad_argument/error`}{
#'   \describe{
#'     \item{package}{`{t0}`}
#'     \item{class}{`t0:bad_argument`}
#'     \item{type}{**error**}
#'   }
#'   x should be `TRUE`
#'  }
#'
#' @seealso [cnd::cnd-package] [cnd::condition]
#' @keywords internal
#'
NULL
