
# exports -----------------------------------------------------------------

#' Document your conditions
#'
#' Documents your [conditions()] and [cnd::conditions()]
#'
#' @param package The package to document
#' @param registry The name of the registry
#' @param path The path to save the documentation
#' @param cleanup If `FALSE` will not remove files containing `# % Generated by
#'   cnd: do not edit by hand`
#'
#' @export
#' @returns A `character` vector`
cnd_document <- function(
    package = get_package(),
    registry = package,
    path = file.path("R", paste0(package, "-cnd-conditions.R")),
    cleanup = TRUE
) {
  force(package)
  force(path)
  conds <- conditions(package = package, registry = registry)

  res <- fmt(
    sub("[@]noRd", "@export", cnd_documentation_fmt),
    package = package,
    # nolint start: line_length_linter.
    aliases1 = collapse(vapply(conds, cget, NA_character_, "class"), sep = " "),
    aliases2 = collapse(vapply(conds, cget, NA_character_, ".class"), sep = " "),
    aliases3 = collapse(vapply(conds, `format.cnd::condition_generator`, NA_character_), sep = " "),
    # nolint end: line_length_linter.
    cnd_section_describe = collapse(
      vapply(
        conds,
        function(c) {
          fmt(
            sub("@keywords internal", "", cnd_section_describe_fmt),
            form = format(c),
            pkg = cget(c, "package"),
            cls = cget(c, "class"),
            typ = cget(c, "type"),
            help = if (is.null(h <- cget(c, "help"))) {
              "#'"
            } else {
              paste0("#'   ", clean_text(h), collapse = "\n")
            }
          )
        },
        NA_character_
      )
    )
  )

  if (is.character(path)) {
    dir <- dirname(path)
    if (dir.exists(dir)) {
      cnd_files <- filter2(
        list.files(dir, full.names = TRUE),
        function(p) {
          readLines(p, n = 1, warn = FALSE) ==
            "# % Generated by cnd: do not edit by hand"
        }
      )
    }

    cnd(cond_cnd_generated_cleanup(cnd_files))
    try(file.remove(cnd_files), silent = TRUE)
    cnd(cond_cnd_generated_write(path))
  }

  cat(res, file = path, sep = "")
}

#' @export
#' @rdname cnd_document
#' @param fun The name of a function
cnd_section <- function(fun) {
  conds <- conditions(fun)
  fmt(
    cnd_section_fmt,
    conds = collapse(
      vapply(
        conds,
        function(c) {
          fmt(
            cnd_section_item_fmt,
            pkg = cget(c, "package"),
            form = format(c),
            help = cget(c, "help") %||% ""
          )
        },
        NA_character_
      )
    ),
    pkgs = collapse(
      vapply(
        unique(vapply(conds, cget, NA_character_, "package")),
        function(p) fmt("[{pkg}-cnd-conditions]", pkg = p),
        NA_character_
      )
    ),
    sep = ", "
  )
}


# fmts --------------------------------------------------------------------

## cnd_document() ----

cnd_documentation_fmt <- "# % Generated by cnd: do not edit by hand

#' @name {package}-cnd-conditions
#' @aliases {package}-cnd-conditions {aliases1} {aliases2} {aliases3}
#' @title Conditions for `{package}`
#'
#' @details
#'  The following conditions are defined in the `{{package}}` package.
#'
#' @section [`{cnd}`][cnd::cnd-package]:
#'  These conditions are made with the `{cnd}` package though the use of
#'  [cnd::condition()].
#'
#' @section `{{package}}` conditions:
#' {cnd_section_describe}
#'
#' @seealso [cnd::cnd-package] [cnd::condition]
#' @noRd
#' @keywords internal
'_PACKAGE'
"

cnd_section_describe_fmt <- "
#' @keywords internal
#'   \\subsection{`{form}`}{
#'   \\describe{
#'     \\item{package}{`{{pkg}}`}
#'     \\item{class}{`{cls}`}
#'     \\item{type}{**{typ}**}
#'   }
{help}
#'   }
#'"

## cnd_section() ----

cnd_section_fmt <- "
Conditions are generated through the [`{cnd}`][cnd::cnd-package] package.
The following conditions are associated with this function:

\\describe{
  {conds}
}

For more conditions, see: {pkgs}
"

cnd_section_item_fmt <- "
  \\item{[`{form}`][{pkg}-cnd-conditions]}{
    {help}
  }
"

# conditions --------------------------------------------------------------

cond_cnd_generated_cleanup <- function() {}
delayedAssign(
  "cond_cnd_generated_cleanup",
  condition(
    "cnd_generated_cleanup",
    type = "condition",
    package = "cnd",
    exports = "cnd_document",
    message = function(paths) c(
      "Removing the following cnd generated files:",
      paste0("  ", paths)
    )
  )
)

cond_cnd_generated_write <- function() {}
delayedAssign(
  "cond_cnd_generated_write",
  condition(
    "cnd_generated_write",
    type = "condition",
    package = "cnd",
    exports = "cnd_document",
    message = function(path) c(
      "Writing to the following path: ",
      paste0("  ", path),
      "do not edit by hand"
    )
  )
)
