# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check.yaml

permissions: read-all

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  R_KEEP_PKG_SOURCE: yes

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix=$(jq -c . <<EOF
        {
          "config": [
            {"os": "macos-latest", "r": "release"},
            {"os": "windows-latest", "r": "release"},
            {"os": "ubuntu-latest", "r": "devel", "http-user-agent": "release"},
            {"os": "ubuntu-latest", "r": "release"},
            {"os": "ubuntu-latest", "r": "oldrel-1"}
          ]
        }
        EOF
        )" >> "$GITHUB_OUTPUT"
  setup:
    name: setup ${{ matrix.config.os }} (${{ matrix.config.r }})
    needs: define-matrix

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

  R-CMD-check-cnd:
    name: cnd ${{ matrix.config.os }} (${{ matrix.config.r }})
    needs: setup

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'

  R-CMD-check-cndSimpleExample:
    name: cndSimpleExample ${{ matrix.config.os }} (${{ matrix.config.r }})
    needs: R-CMD-check-cnd

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: tools/cndSimpleExample
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: tools/cndSimpleExample
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
